# === coturn 配置 — teleop 项目 ===
listening-port=3478
listening-ip=0.0.0.0
relay-ip=172.21.124.70
external-ip=39.102.113.104/172.21.124.70
lt-cred-mech
realm=teleop
user=remote:Wawjxyz3!
syslog
verbose
fingerprint
min-port=49152
max-port=65535
no-tls
no-dtls
